### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by dv-blk** [Syphdias/switch-pulseaudio-sink#4]
This was the only script I could find that worked to switch my sources with pipewire and pulseeffects sinks for me.

I'm not sure what the python portion does, I just pulled out the bash script out and commented the last while statement to retain my pulseeffects sinks.

I just wanted to drop a star and acknowledge your work here!

**Comment by Syphdias** [comment]
Thank you for letting me know, @dv-blk, very much appreciated!

The original bash script aimed to do a few things:
* toggle default sink through filtered list of sinks
* provide input to select a sink instead of toggling to set a default sink
* switch all input sinks to new default sink
* avoid dependencies

The python script is functional but not well tested yet. Also not clean enough, which is why I didn't expand the README yet.
It does more than the bash script but has no interactivity. It unifies and generalizes another script I used to switch profiles of sinks.

I would like to know what you value in the script. Do you use it to toggle through sinks? Or do you use the dmenu?

**Comment by dv-blk** [comment]
I'm currently using the dmenu prompt to to toggle between my headphones and speakers. Eventually I'll create a custom widget for to integrate this script into awesomewm. 

I value that it actually works -- I don't use a DE and I failed to find any standalone packages where I could toggle this programmatically with a simple GUI. Pavucontrol works, but it doesn't have an option to minimize to tray or simply toggle audio source without needing to open the app and switch to the playback tab, nor does it have a cli interface.

I will likely modify the dmenu portion of the script to take a bash argument that the buttons in my widget will supply.

**Comment by Syphdias** [comment]
Hey @dv-blk, thank you for letting me know!

I can relate to light weight DEs/WMs – I use i3wm myself.

A few remarks:
1. You used the word "toggle" and wanted to make `dmenu` pick a button. Did you notice the script has a toggle flag `-t` which automatically picks the next matching, not-already-default sink? Is that what you want?
2. As I understand it pavucontrol itself is a frontend for the pulseaudio interface (possibly via libpulse but I have not idea what soever). If you want a cli tool to interact with it you can use `pactl` (like I did in the script, provided by `libpulse` on my distro) or `pacmd` (provided by `pulseaudio` in my distro)
3. pavucontrol doesn't have a tray icon but there is `pasystray` which can set default sink and lots of other things including launching pavucontrol.

PS: Sorry, for the delayed answer. I was indisposed for a time.
